apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: example-app-2
  labels:
    app.kubernetes.io/name: example-app-2
    app.kubernetes.io/instance: example-app-2
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: appme-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`app2.example.com`)
    kind: Rule
    services:
    - name: example-app-2
      port: 80 