apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-1
spec:
  selector:
    matchLabels:
      app: example-app-1
  template:
    metadata:
      labels:
        app: example-app-1
    spec:
      containers:
      - name: example-app-1
        image: docker.io/morawskioz/example-app-1:0.0.1
        ports:
        - containerPort: 8080 