apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-appme-2
  namespace: appme
spec:
  project: appme
  source:
    repoURL: https://github.com/morawskiOZ/appme-k8s.git
    targetRevision: HEAD
    path: gitops/apps/example-app-2
    kustomize:
      images:
        - docker.io/morawskioz/example-app-2=docker.io/morawskioz/example-app-2:v1.2.0
  destination:
    namespace: appme
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true