apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-inline-guestbook
  namespace: appme
spec:
  project: appme
  source:
    repoURL: https://github.com/morawskiOZ/appme-k8s.git
    targetRevision: HEAD
    path: gitops/apps/guestbook
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true