apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-inline-guestbook
  namespace: appme
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: appme
  source:
    repoURL: https://github.com/morawskiOZ/appme-k8s.git
    targetRevision: main
    path: gitops/apps
    kustomize:
      components:
        - components/example-app-1
        - components/example-app-2
      images:
        - example-app-1=docker.io/morawskioz/example-app-1:1.0.0
        - example-app-2=docker.io/morawskioz/example-app-2:1.0.0
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 