apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: example-app-1
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`app1.example.com`)
    kind: Rule
    services:
    - name: example-app-1
      port: 80 