apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-APPME-2
  namespace: appme
spec:
  project: appme
  source:
    repoURL: https://github.com/morawskiOZ/appme-k8s.git
    targetRevision: HEAD
    path: gitops/apps
    kustomize:
      components:
        - components/example-app-2
      images:
        - example-app-2=docker.io/morawskioz/example-app-2:1.0.1
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 