apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-apps
  namespace: appme
spec:
  project: appme
  source:
    repoURL: https://github.com/morawskiOZ/appme-k8s.git
    targetRevision: HEAD
    path: gitops/argocd/applications/prev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true