apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: example-app-1
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`k8s.appunow.com`) && PathPrefix(`/app1`)
    kind: Rule
    middlewares:
    - name: example-app-1-stripprefix
    services:
    - name: example-app-1
      port: 80 