apiVersion: v1
kind: Service
metadata:
  name: example-app-1
  labels:
    app.kubernetes.io/name: example-app-1
    app.kubernetes.io/instance: example-app-1
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: appme-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: example-app-1
  ports:
  - port: 80
    targetPort: 8080 