apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml

components:
  - components/example-app-1
  - components/example-app-2 